### ISSUE TITLE
make sure images is build with last version of code

### ISSUE THREAD

**Issue by PhilippeAccorsi** [CollaboraOnline/Docker#10]
I seen that docker build command not use `--no-cache` parameter to make sure every new image build use all new LibreOffice packages available. Is it not better to use `--no-cache` in docker build command to make sure no mistake can be done ? (if we have create an image locally before wanted to create a latest image)

Command like this `docker build --no-cache --build-arg SECRET_KEY=<your secret URL part from https://support.collaboraoffice.com, e.g. Example-413539ece39485afc35b4a469adfde0a279d2fd2> -t collabora/online-base .`

I have created an image with release 4.2.1 two week ago (before communication about release 4.2.2), and today I have started creation of new image to use release 4.2.2. Docker build command just show this:

~~~
Sending build context to Docker daemon  9.728kB
Step 1/7 : FROM ubuntu:18.04
 ---> 4e5021d210f6
Step 2/7 : ARG SECRET_KEY
 ---> Using cache
 ---> f0e8bd691f8b
Step 3/7 : ARG REPOS
 ---> Using cache
 ---> e7022d7fd649
Step 4/7 : ADD /scripts/install-libreoffice.sh /
 ---> Using cache
 ---> 38fe3c407dc1
Step 5/7 : ADD /scripts/start-libreoffice.sh /
 ---> Using cache
 ---> b7f4bd647d87
Step 6/7 : RUN bash install-libreoffice.sh
 ---> Using cache
 ---> 203b5046c27c
Step 7/7 : RUN rm -rf /install-libreoffice.sh
 ---> Using cache
 ---> af103c1bc3e9
Successfully built af103c1bc3e9
Successfully tagged collabora/online-base:latest
~~~

So if I not add `--no-cache` parameter, new image can't be build correctly.

**Comment by timar** [comment]
I'm not sure what can be done with this issue. Do you have a suggestion?

**Comment by PhilippeAccorsi** [comment]
I think its better to replace `docker build --build-arg SECRET_KEY=<your secret URL part from https://support.collaboraoffice.com, e.g. Example-413539ece39485afc35b4a469adfde0a279d2fd2> -t collabora/online-base .`

**by** 

`docker build --no-cache --build-arg SECRET_KEY=<your secret URL part from https://support.collaboraoffice.com, e.g. Example-413539ece39485afc35b4a469adfde0a279d2fd2> -t collabora/online-base .` in README.md
