### ISSUE TITLE
Docker Capabilities

### ISSUE THREAD

**Issue by Scriptkiddi** [CollaboraOnline/Docker#7]
Hey guys,

I'm getting 
> [ loolforkit ] FTL  Capability cap_sys_chroot is not set for the loolforkit program.
> [ loolforkit ] FTL  Capability cap_mknod is not set for the loolforkit program.
> [ loolforkit ] FTL  Capability cap_fowner is not set for the loolforkit program.

when I'm running the docker container in a vm that has its root file system on nfs mount.
Any ideas how to fix it? Or any chance that those capabilities could be fixed?

**Comment by loxK** [comment]
I don't think you can. What type of VM is it ?

For example LXD will not allow such things even in a privileged container

**Comment by Scriptkiddi** [comment]
its a normal debian bootet over nfs with the nosuid flag set, my workaround so far was to extract the docker image into an ansible role 
and set a systemd service with the child root pointed to tmp
[Unit]
Description=LibreOffice Online WebSocket Daemon for Collabora
After=network.target

[Service]
ExecStart=/usr/bin/loolwsd --version --o:sys_template_path=/opt/lool/systemplate --o:lo_template_path=/opt/collaboraoffice6.0 --o:child_root_path=/tmp/child-roots --o:file_server_root_path=/usr/share/loolwsd
AmbientCapabilities=CAP_SYS_CHROOT CAP_SYS_MKNOD CAP_MKNOD CAP_FOWNER
User=lool
KillMode=control-group
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by Scriptkiddi** [comment]
So for anybody finding this as far as I could trace the bug collabora on a NFS filesystem which does not support capabilities is a problem but the capabilities check can be turn of by passing --o:security.capabilities=false to loolwsd, that disables the capabilities check and you can run it
For those that are running docker on a host that has a nfs filesystem its the same problem
