### ISSUE TITLE
Merge changes from CODE

### ISSUE THREAD

**Issue by ralfbecker** [CollaboraOnline/Docker#9]
Hi Timar,

can you merge the changes from CODE:
- Ubuntu 18.04 as base
- root-less
- ...

Or are there reasons to not merge them - apart from time ;)

Ralf

**Comment by timar** [comment]
Hi Ralf, 

I'll do. I'll also switch to Collabora Online 4.2.0, when it's out (this week). 

Best regards,
Andras

**Comment by ralfbecker** [comment]
Thanks :)

Was my plan to, to release 4.2.0 with an Ubuntu 18.04 container.

Root-less container makes sense, thought it's some trouble, if the existing config-files volume have no other rights.

Ralf
